# docker run -d -e ACCEPT_EULA=Y -e SA_PASSWORD=TokyoJoe138! -p 1433:1433 mcr.microsoft.com/mssql/server:2022-latest
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TokyoJoe138!
    ports:
      - 1433:1433